// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzlsmbcxsalrtwddeojj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6bHNtYmN4c2FscnR3ZGRlb2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzExMTgsImV4cCI6MjA2MDgwNzExOH0.1rzK-eg_cY3agr1LwGh4b6Z4rNDhcyw1ylCWlJZVRXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);